<?php

namespace App\Services\Deployment;

use App\Models\Application;
use Exception;

class LegacyConfigService
{
    public function __construct(protected SSHService $ssh) {}

    /**
     * Gère la synchronisation des fichiers critiques pour le mode Legacy.
     * Pour l'instant : uniquement le fichier .env adapté.
     */
    public function syncConfiguration(Application $app): void
    {
        $targetPath = $app->target_path;
        
        if (empty($targetPath)) {
            throw new Exception("Target path is missing for legacy configuration sync.");
        }

        $targetPathEscaped = escapeshellarg($targetPath);

        // 1. S'assurer que le dossier existe
        $this->ssh->exec("mkdir -p {$targetPathEscaped}");

        // 2. Générer et écrire le .env
        $this->syncEnvironmentVariables($app, $targetPath);
    }

    /**
     * Génère un fichier .env adapté au mode Legacy (Host natif).
     */
    protected function syncEnvironmentVariables(Application $app, string $appPath): void
    {
        $serverIp = $app->server->ip ?? '127.0.0.1';
        $domain = $app->domain ?: "{$app->sanitized_name}.{$serverIp}.sslip.io";

        $envVars = [
            'APP_NAME' => $app->sanitized_name,
            'APP_ENV' => 'production',
            'APP_URL' => "https://{$domain}",
            'PORT' => '80',
        ];

        // Injection des bases de données
        $databases = $app->databases()->with('server')->get();
        $dbTypesFound = [];
        
        foreach ($databases as $db) {
            $type = $db->type;
            $dbTypesFound[$type] = ($dbTypesFound[$type] ?? 0) + 1;
            
            $isSameServer = $db->server_id === $app->server_id;
            $host = $isSameServer ? '127.0.0.1' : $db->server->ip;
            
            $port = ($type === 'mysql' || $type === 'mariadb') ? '3306' : ($type === 'redis' ? '6379' : '5432');
            
            $isSecondary = $dbTypesFound[$type] > 1;
            $slugName = strtoupper(preg_replace('/[^a-z0-9]/i', '_', $db->name));
            $prefix = $isSecondary ? "{$slugName}_" : "";

            if ($type === 'redis') {
                $envVars["{$prefix}REDIS_HOST"] = $host;
                $envVars["{$prefix}REDIS_PORT"] = $port;
                if ($db->db_password) {
                    $envVars["{$prefix}REDIS_PASSWORD"] = $db->db_password;
                    $envVars["{$prefix}REDIS_URL"] = "redis://:{$db->db_password}@{$host}:{$port}";
                } else {
                    $envVars["{$prefix}REDIS_URL"] = "redis://{$host}:{$port}";
                }
            } else {
                $laravelType = ($type === 'postgres') ? 'pgsql' : $type;
                $envVars["{$prefix}DB_CONNECTION"] = $laravelType;
                $envVars["{$prefix}DB_HOST"] = $host;
                $envVars["{$prefix}DB_PORT"] = $port;
                $envVars["{$prefix}DB_DATABASE"] = $db->db_name;
                $envVars["{$prefix}DB_USERNAME"] = $db->db_user;
                $envVars["{$prefix}DB_PASSWORD"] = $db->db_password;
                
                $auth = "{$db->db_user}:{$db->db_password}";
                $envVars["{$prefix}DATABASE_URL"] = "{$type}://{$auth}@{$host}:{$port}/{$db->db_name}";
            }
        }

        // Variables utilisateur
        $userVars = $app->environmentVariables()->get();
        foreach ($userVars as $var) {
            $envVars[$var->key] = $var->value;
        }

        $content = "# Generated by VPSly (Legacy Mode)\n";
        foreach ($envVars as $key => $value) {
            $content .= "{$key}=\"{$value}\"\n";
        }

        $this->writeAtomicRemoteFile($appPath . '/.env', $content);
    }

    protected function writeAtomicRemoteFile(string $filePath, string $content): void
    {
        $tmpPath = $filePath . '.tmp.' . bin2hex(random_bytes(8));
        $this->ssh->upload($tmpPath, $content);
        
        $filePathEscaped = escapeshellarg($filePath);
        $tmpPathEscaped = escapeshellarg($tmpPath);
        
        $this->ssh->exec("chmod 600 {$tmpPathEscaped} && mv {$tmpPathEscaped} {$filePathEscaped}");
    }
}
