<?php

namespace App\Services\Deployment;

use App\Models\Application;
use Illuminate\Support\Facades\Log;
use Exception;

class LegacyConfigService
{
    public function __construct(protected SSHService $ssh) {}

    /**
     * Gère la synchronisation des fichiers critiques pour le mode Legacy.
     */
    public function syncConfiguration(Application $app): void
    {
        $this->ssh->connect($app->server);
        
        $targetPath = $app->target_path;
        
        if (empty($targetPath)) {
            Log::warning("[LegacyConfig] Skipping sync: Target path is missing for App ID {$app->id}");
            return;
        }

        $targetPathEscaped = escapeshellarg($targetPath);

        // 1. S'assurer que le dossier existe
        $this->ssh->exec("mkdir -p {$targetPathEscaped}");

        // 2. Générer et écrire le .env (Miroir strict de la base de données)
        $this->syncEnvironmentVariables($app, $targetPath);
    }

    /**
     * Importe les variables d'un fichier .env (ou .env.example) distant vers la base de données.
     * C'est ici que VPSly "apprend" la configuration du serveur.
     */
    public function importFromRemote(Application $app, ?string $path = null): int
    {
        $this->ssh->connect($app->server);
        $basePath = rtrim($path ?? $app->target_path, '/');
        $remoteEnvPath = $basePath . '/.env';
        $remoteExamplePath = $basePath . '/.env.example';
        
        try {
            // Tentative de lecture du .env, fallback sur .env.example
            $content = $this->ssh->exec("cat " . escapeshellarg($remoteEnvPath));
            
            if (empty(trim($content)) || str_contains($content, 'No such file or directory')) {
                Log::info("[LegacyConfig] .env not found, trying .env.example for App {$app->id}");
                $content = $this->ssh->exec("cat " . escapeshellarg($remoteExamplePath));
            }

            if (empty(trim($content)) || str_contains($content, 'No such file or directory')) {
                return 0;
            }

            $lines = explode("\n", $content);
            $importedCount = 0;

            foreach ($lines as $line) {
                $line = trim($line);
                
                // On ignore les commentaires et lignes vides
                if (empty($line) || str_starts_with($line, '#')) continue;

                if (str_contains($line, '=')) {
                    [$key, $value] = explode('=', $line, 2);
                    $key = trim($key);
                    $value = trim($value);

                    // Nettoyage des guillemets
                    if (str_starts_with($value, '"') && str_ends_with($value, '"')) $value = substr($value, 1, -1);
                    elseif (str_starts_with($value, "'") && str_ends_with($value, "'")) $value = substr($value, 1, -1);

                    // On n'importe que si la clé n'existe pas déjà pour ne pas écraser les saisies manuelles récentes
                    if (!empty($key) && preg_match('/^[A-Z0-9_]+$/i', $key)) {
                        $exists = $app->environmentVariables()->where('key', strtoupper($key))->exists();
                        
                        if (!$exists) {
                            $app->environmentVariables()->create([
                                'key' => strtoupper($key),
                                'value' => $value,
                                'is_secret' => true
                            ]);
                            $importedCount++;
                        }
                    }
                }
            }

            return $importedCount;

        } catch (Exception $e) {
            Log::error("[LegacyConfig] Failed to import variables for App {$app->id}: " . $e->getMessage());
            return 0;
        } finally {
            $this->ssh->disconnect();
        }
    }

    /**
     * Génère un fichier .env qui est le REFLET EXACT de la base de données.
     * VPSly n'injecte plus RIEN de lui-même.
     */
    protected function syncEnvironmentVariables(Application $app, string $appPath): void
    {
        $variables = $app->environmentVariables()->orderBy('key')->get();
        
        $content = "# >>> GENERATED BY VPSLY (Mirror Mode)\n";
        $content .= "# Source: Dashboard Database\n";
        $content .= "# Last Sync: " . now()->toDateTimeString() . "\n\n";

        foreach ($variables as $var) {
            $key = strtoupper($var->key);
            $value = $var->value ?? '';

            // Protection des valeurs sensibles ou complexes
            if (preg_match('/\s|[#$!*()]/', $value)) {
                $content .= "{$key}=\"{$value}\"\n";
            } else {
                $content .= "{$key}={$value}\n";
            }
        }

        $this->writeAtomicRemoteFile($appPath . '/.env', $content);
        Log::info("[LegacyConfig] .env mirror sync completed for App: {$app->name}");
    }

    /**
     * Écriture sécurisée et atomique pour éviter de corrompre le .env en cas de coupure SSH.
     */
    protected function writeAtomicRemoteFile(string $filePath, string $content): void
    {
        $tmpPath = $filePath . '.tmp.' . bin2hex(random_bytes(8));
        $this->ssh->upload($tmpPath, $content);
        
        $filePathEscaped = escapeshellarg($filePath);
        $tmpPathEscaped = escapeshellarg($tmpPath);
        
        // MV est atomique sur Linux
        $this->ssh->exec("chmod 600 {$tmpPathEscaped} && mv {$tmpPathEscaped} {$filePathEscaped}");

        // Fix permissions pour le serveur web (Legacy)
        $this->ssh->exec("sudo chown www-data:www-data {$filePathEscaped} 2>/dev/null || true");
        $this->ssh->exec("sudo chmod 640 {$filePathEscaped} 2>/dev/null || chmod 600 {$filePathEscaped}");
    }
}
